# -*- coding: utf-8 -*-
"""3.1 modelo arima

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxHFzrJXdI4E-Qq1bBW922-QrH1JiFHu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA

# 1. Generar datos simulados
np.random.seed(42)
data = np.cumsum(np.random.randn(100)) + 50
df = pd.DataFrame(data, columns=['value'])

# 2. Visualizar los datos
plt.figure(figsize=(10, 4))
plt.plot(df['value'])
plt.title('Datos simulados')
plt.xlabel('Tiempo')
plt.ylabel('Valor')
plt.grid(True)
plt.show()

# 3. Crear y ajustar el modelo ARIMA
model = ARIMA(df['value'], order=(5, 1, 0))  # (p,d,q)
model_fit = model.fit()

# 4. Mostrar resumen del modelo
print(model_fit.summary())

# 5. Predicción futura
forecast = model_fit.forecast(steps=10)
print("Predicción para los próximos 10 pasos:")
print(forecast)

# 6. Visualizar la predicción
plt.figure(figsize=(10, 4))
plt.plot(df['value'], label='Datos históricos')
plt.plot(np.arange(len(df), len(df) + len(forecast)), forecast, label='Predicción', color='red')
plt.title('Predicción con el modelo ARIMA')
plt.xlabel('Tiempo')
plt.ylabel('Valor')
plt.legend()
plt.grid(True)
plt.show()